import type {
  Plan,
  Role,
  SaleStatus,
  PaymentMethod,
  PurchaseStatus,
  ExpenseCategory,
  Permission,
} from "./enums";

export interface BusinessDto {
  id: string;
  name: string;
  plan: Plan;
  legalName: string | null;
  taxId: string | null;
  registrationNumber: string | null;
  address: string | null;
  phone: string | null;
  email: string | null;
  website: string | null;
  /** ISO 4217, 0-2 decimal places. */
  currency: string;
  /** Decimal string, e.g. "19". */
  defaultTaxRate: string;
  receiptHeader: string | null;
  receiptFooter: string | null;
  invoiceFooter: string | null;
  /** Relative to the API root (prefix with /api in the web app); null without a logo. */
  logoUrl: string | null;
}

export type UpdateBusinessDto = Partial<
  Pick<
    BusinessDto,
    | "name"
    | "legalName"
    | "taxId"
    | "registrationNumber"
    | "address"
    | "phone"
    | "email"
    | "website"
    | "currency"
    | "receiptHeader"
    | "receiptFooter"
    | "invoiceFooter"
  >
> & { defaultTaxRate?: number };

export interface UpdateStoreDto {
  name?: string;
  address?: string | null;
  phone?: string | null;
  timezone?: string;
}

export interface StoreDto {
  id: string;
  businessId: string;
  name: string;
  address: string | null;
  phone: string | null;
  timezone: string;
  isActive: boolean;
}

export interface UserDto {
  id: string;
  businessId: string;
  email: string;
  firstName: string;
  lastName: string;
  role: Role;
  isActive: boolean;
  /** Only present on login/register responses; absent on older persisted sessions. */
  emailVerified?: boolean;
  accessibleStoreIds: string[];
}

export type EffectivePermissionsDto = Record<Permission, boolean>;

export interface UpdateUserPermissionDto {
  permission: Permission;
  granted?: boolean | null;
}

export interface LoginRequestDto {
  email: string;
  password: string;
}

export interface RegisterRequestDto {
  businessName: string;
  storeName: string;
  firstName: string;
  lastName: string;
  email: string;
  password: string;
  /** IANA zone, e.g. "Europe/Paris"; the API defaults to UTC. */
  timezone?: string;
}

export interface LoginResponseDto {
  accessToken: string;
  user: UserDto;
  stores: StoreDto[];
  business: BusinessDto;
}

export interface CategoryDto {
  id: string;
  businessId: string;
  name: string;
}

export interface ProductDto {
  id: string;
  businessId: string;
  categoryId: string | null;
  sku: string;
  barcode: string | null;
  name: string;
  description: string | null;
  costPrice: string;
  sellPrice: string;
  taxRate: string;
  isActive: boolean;
}

export interface CreateProductDto {
  categoryId?: string | null;
  sku: string;
  barcode?: string | null;
  name: string;
  description?: string | null;
  costPrice: number;
  sellPrice: number;
  taxRate?: number;
}

export interface InventoryItemDto {
  id: string;
  storeId: string;
  productId: string;
  product: ProductDto;
  quantity: number;
  reorderLevel: number;
}

export interface AdjustStockDto {
  quantity: number;
  reorderLevel?: number;
}

export interface CreateCustomerDto {
  name: string;
  phone?: string;
  email?: string;
}

export interface CustomerDto {
  id: string;
  businessId: string;
  name: string;
  phone: string | null;
  email: string | null;
  address: string | null;
  taxId: string | null;
}

export interface SaleLineItemInputDto {
  productId: string;
  quantity: number;
  /** Offline sales only: the price and tax rate (%) the till used. */
  unitPrice?: number;
  taxRate?: number;
}

export interface SalePaymentInputDto {
  method: PaymentMethod;
  amount: number;
  /** Only meaningful for a CASH leg; omitted means "exact cash, no change". */
  tendered?: number;
}

export interface CreateSaleDto {
  storeId: string;
  customerId?: string | null;
  /** Ad-hoc address to email the receipt to. If omitted and a customer with
   * an email is attached, that email is used automatically. */
  receiptEmail?: string;
  payments: SalePaymentInputDto[];
  lineItems: SaleLineItemInputDto[];
  /** Idempotency key generated by the till before the first attempt. */
  clientId?: string;
  /** The desktop till that rang the sale up. */
  terminalId?: string;
  /** Set when the sale was rung up without reaching the server. */
  offline?: { createdAt: string };
}

export interface SalePaymentDto {
  id: string;
  method: PaymentMethod;
  amount: string;
  tendered: string | null;
  change: string | null;
}

export interface SaleLineItemDto {
  id: string;
  productId: string;
  product: ProductDto;
  quantity: number;
  unitPrice: string;
  taxAmount: string;
  discountAmount: string;
  lineTotal: string;
}

export interface SupplierDto {
  id: string;
  businessId: string;
  name: string;
  contactName: string | null;
  phone: string | null;
  email: string | null;
  address: string | null;
}

export interface CreateSupplierDto {
  name: string;
  contactName?: string;
  phone?: string;
  email?: string;
  address?: string;
}

export interface EmployeeDto {
  id: string;
  businessId: string;
  storeId: string | null;
  store: StoreDto | null;
  userId: string | null;
  user: StaffAccessDto | null;
  firstName: string;
  lastName: string;
  position: string | null;
  phone: string | null;
  email: string | null;
  hireDate: string | null;
  wage: string | null;
  isActive: boolean;
}

export interface CreateEmployeeDto {
  firstName: string;
  lastName: string;
  position?: string;
  phone?: string;
  email?: string;
  hireDate?: string;
  wage?: number;
  storeId?: string;
  userId?: string;
  /** Owner only: create a login for the employee in the same request. */
  login?: StaffLoginDto;
}

/** Roles an owner can give a staff login. */
export type StaffRole = "CASHIER" | "MANAGER";

/** Exactly one of `password` or `sendInvite: true`. */
export interface StaffLoginDto {
  email: string;
  role: StaffRole;
  storeIds: string[];
  password?: string;
  sendInvite?: boolean;
}

export interface StaffAccessDto {
  id: string;
  email: string;
  role: Role;
  isActive: boolean;
  storeIds: string[];
}

export interface UpdateStaffAccessDto {
  role?: StaffRole;
  storeIds?: string[];
  isActive?: boolean;
}

export interface PurchaseLineItemInputDto {
  productId: string;
  quantity: number;
  unitCost: number;
}

export interface CreatePurchaseDto {
  storeId: string;
  supplierId: string;
  lineItems: PurchaseLineItemInputDto[];
}

export interface PurchaseLineItemDto {
  id: string;
  productId: string;
  product: ProductDto;
  quantity: number;
  unitCost: string;
  lineTotal: string;
}

export interface PurchaseDto {
  id: string;
  storeId: string;
  supplierId: string;
  supplier: SupplierDto;
  purchaseNumber: string;
  subtotal: string;
  taxTotal: string;
  total: string;
  status: PurchaseStatus;
  createdAt: string;
  lineItems: PurchaseLineItemDto[];
}

export interface TransferLineItemInputDto {
  productId: string;
  quantity: number;
}

export interface CreateTransferDto {
  fromStoreId: string;
  toStoreId: string;
  note?: string;
  lineItems: TransferLineItemInputDto[];
}

export interface TransferLineItemDto {
  id: string;
  productId: string;
  product: ProductDto;
  quantity: number;
}

export interface TransferStoreSummaryDto {
  id: string;
  name: string;
}

export interface StockTransferDto {
  id: string;
  fromStoreId: string;
  fromStore: TransferStoreSummaryDto;
  toStoreId: string;
  toStore: TransferStoreSummaryDto;
  transferredById: string;
  note: string | null;
  createdAt: string;
  lineItems: TransferLineItemDto[];
}

export interface CreateExpenseDto {
  storeId: string;
  category: ExpenseCategory;
  description?: string;
  amount: number;
  incurredAt?: string;
}

export interface ExpenseDto {
  id: string;
  storeId: string;
  category: ExpenseCategory;
  description: string | null;
  amount: string;
  incurredAt: string;
  createdAt: string;
}

export interface ReturnLineItemInputDto {
  productId: string;
  quantity: number;
}

export interface CreateReturnDto {
  storeId: string;
  saleId: string;
  reason?: string;
  lineItems: ReturnLineItemInputDto[];
}

export interface ReturnLineItemDto {
  id: string;
  productId: string;
  product: ProductDto;
  quantity: number;
  unitPrice: string;
  lineTotal: string;
}

export interface ReturnDto {
  id: string;
  saleId: string;
  storeId: string;
  reason: string | null;
  totalRefund: string;
  createdAt: string;
  lineItems: ReturnLineItemDto[];
}

export interface ReportSummaryDto {
  revenue: number;
  profit: number;
  orderCount: number;
  avgOrderValue: number;
  revenueDeltaPct: number | null;
  profitDeltaPct: number | null;
  orderCountDeltaPct: number | null;
  avgOrderValueDeltaPct: number | null;
}

export interface SalesTrendPointDto {
  date: string;
  revenue: number;
  orderCount: number;
}

export interface TopProductReportDto {
  productId: string;
  name: string;
  quantitySold: number;
  revenue: number;
}

export interface LowStockReportItemDto {
  id: string;
  storeId: string;
  productId: string;
  product: ProductDto;
  quantity: number;
  reorderLevel: number;
}

export interface InsightHighlightDto {
  title: string;
  detail: string;
}

export interface RestockSuggestionDto {
  productName: string;
  reason: string;
}

export interface BusinessInsightsDto {
  summary: string;
  highlights: InsightHighlightDto[];
  restockSuggestions: RestockSuggestionDto[];
}

export interface StoreComparisonDto {
  storeId: string;
  storeName: string;
  revenue: number;
  profit: number;
  orderCount: number;
}

export interface SaleDto {
  id: string;
  storeId: string;
  cashierId: string;
  customerId: string | null;
  receiptNumber: string;
  subtotal: string;
  taxTotal: string;
  discountTotal: string;
  total: string;
  paymentMethod: PaymentMethod;
  amountTendered: string | null;
  changeDue: string | null;
  status: SaleStatus;
  createdAt: string;
  createdOffline?: boolean;
  terminalId?: string | null;
  /** Client-only: a receipt built on the till for a sale still waiting in the outbox. */
  queued?: boolean;
  lineItems: SaleLineItemDto[];
  payments: SalePaymentDto[];
}

/** Seller details frozen when an invoice is issued. */
export interface SellerSnapshotDto {
  name: string;
  legalName: string | null;
  taxId: string | null;
  registrationNumber: string | null;
  address: string | null;
  phone: string | null;
  email: string | null;
  website: string | null;
  currency: string;
  logoUrl: string | null;
  invoiceFooter: string | null;
  store: { id: string; name: string; address: string | null; phone: string | null };
}

export interface InvoiceDto {
  id: string;
  businessId: string;
  saleId: string;
  year: number;
  sequence: number;
  /** e.g. INV-2026-0001 */
  number: string;
  issuedAt: string;
  seller: SellerSnapshotDto;
  buyerName: string;
  buyerAddress: string | null;
  buyerTaxId: string | null;
  buyerEmail: string | null;
  customerId: string | null;
  sale: SaleDto;
}

export interface IssueInvoiceDto {
  buyerName: string;
  buyerAddress?: string;
  buyerTaxId?: string;
  buyerEmail?: string;
  saveToCustomer?: boolean;
}

export interface InvoiceListItemDto {
  id: string;
  number: string;
  issuedAt: string;
  buyerName: string;
  buyerTaxId: string | null;
  sale: { total: string; receiptNumber: string };
}

export interface PagedDto<T> {
  items: T[];
  total: number;
  page: number;
  pageSize: number;
}

export interface TerminalDto {
  id: string;
  storeId: string;
  name: string;
  code: string;
  isActive: boolean;
  createdAt: string;
  lastSeenAt: string | null;
}

export interface CreateTerminalDto {
  storeId: string;
  name: string;
}

export interface UpdateTerminalDto {
  name?: string;
  storeId?: string;
  isActive?: boolean;
}
